# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/JackPaul/OneDrive/Documents/Programs/Projects/eeng498/arminterface-enhancedpwm-lab5/arminterface-enhancedpwm-lab5.srcs/sources_1/bd/zyncepwm/ip/zyncepwm_processing_system7_0_0/zyncepwm_processing_system7_0_0.xci
# IP: The module: 'zyncepwm_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/JackPaul/OneDrive/Documents/Programs/Projects/eeng498/arminterface-enhancedpwm-lab5/arminterface-enhancedpwm-lab5.gen/sources_1/bd/zyncepwm/ip/zyncepwm_processing_system7_0_0/zyncepwm_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zyncepwm_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/JackPaul/OneDrive/Documents/Programs/Projects/eeng498/arminterface-enhancedpwm-lab5/arminterface-enhancedpwm-lab5.srcs/sources_1/bd/zyncepwm/ip/zyncepwm_processing_system7_0_0/zyncepwm_processing_system7_0_0.xci
# IP: The module: 'zyncepwm_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/JackPaul/OneDrive/Documents/Programs/Projects/eeng498/arminterface-enhancedpwm-lab5/arminterface-enhancedpwm-lab5.gen/sources_1/bd/zyncepwm/ip/zyncepwm_processing_system7_0_0/zyncepwm_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zyncepwm_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
