# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/JackPaul/OneDrive/Documents/Programs/Projects/eeng498/oscope-funcgen-lab6/oscope-funcgen-lab6.srcs/sources_1/bd/zyncoscope/ip/zyncoscope_axi_gpio_0_2/zyncoscope_axi_gpio_0_2.xci
# IP: The module: 'zyncoscope_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/JackPaul/OneDrive/Documents/Programs/Projects/eeng498/oscope-funcgen-lab6/oscope-funcgen-lab6.gen/sources_1/bd/zyncoscope/ip/zyncoscope_axi_gpio_0_2/zyncoscope_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zyncoscope_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/JackPaul/OneDrive/Documents/Programs/Projects/eeng498/oscope-funcgen-lab6/oscope-funcgen-lab6.gen/sources_1/bd/zyncoscope/ip/zyncoscope_axi_gpio_0_2/zyncoscope_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zyncoscope_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/JackPaul/OneDrive/Documents/Programs/Projects/eeng498/oscope-funcgen-lab6/oscope-funcgen-lab6.gen/sources_1/bd/zyncoscope/ip/zyncoscope_axi_gpio_0_2/zyncoscope_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'zyncoscope_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/JackPaul/OneDrive/Documents/Programs/Projects/eeng498/oscope-funcgen-lab6/oscope-funcgen-lab6.srcs/sources_1/bd/zyncoscope/ip/zyncoscope_axi_gpio_0_2/zyncoscope_axi_gpio_0_2.xci
# IP: The module: 'zyncoscope_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/JackPaul/OneDrive/Documents/Programs/Projects/eeng498/oscope-funcgen-lab6/oscope-funcgen-lab6.gen/sources_1/bd/zyncoscope/ip/zyncoscope_axi_gpio_0_2/zyncoscope_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zyncoscope_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/JackPaul/OneDrive/Documents/Programs/Projects/eeng498/oscope-funcgen-lab6/oscope-funcgen-lab6.gen/sources_1/bd/zyncoscope/ip/zyncoscope_axi_gpio_0_2/zyncoscope_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zyncoscope_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/JackPaul/OneDrive/Documents/Programs/Projects/eeng498/oscope-funcgen-lab6/oscope-funcgen-lab6.gen/sources_1/bd/zyncoscope/ip/zyncoscope_axi_gpio_0_2/zyncoscope_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'zyncoscope_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
