# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/axi-oscope/acquireToHDMI.xdc

# Block Designs: bd/zyncoscope/zyncoscope.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyncoscope || ORIG_REF_NAME==zyncoscope} -quiet] -quiet

# IP: bd/zyncoscope/ip/zyncoscope_processing_system7_0_0/zyncoscope_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyncoscope_processing_system7_0_0 || ORIG_REF_NAME==zyncoscope_processing_system7_0_0} -quiet] -quiet

# IP: bd/zyncoscope/ip/zyncoscope_epwm_0_1/zyncoscope_epwm_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyncoscope_epwm_0_1 || ORIG_REF_NAME==zyncoscope_epwm_0_1} -quiet] -quiet

# IP: bd/zyncoscope/ip/zyncoscope_epwm_1_1/zyncoscope_epwm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyncoscope_epwm_1_1 || ORIG_REF_NAME==zyncoscope_epwm_1_1} -quiet] -quiet

# IP: bd/zyncoscope/ip/zyncoscope_xbar_1/zyncoscope_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyncoscope_xbar_1 || ORIG_REF_NAME==zyncoscope_xbar_1} -quiet] -quiet

# IP: bd/zyncoscope/ip/zyncoscope_ps7_0_axi_periph_1/zyncoscope_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyncoscope_ps7_0_axi_periph_1 || ORIG_REF_NAME==zyncoscope_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/zyncoscope/ip/zyncoscope_rst_ps7_0_50M_1/zyncoscope_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyncoscope_rst_ps7_0_50M_1 || ORIG_REF_NAME==zyncoscope_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/zyncoscope/ip/zyncoscope_oscope_0_1/zyncoscope_oscope_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyncoscope_oscope_0_1 || ORIG_REF_NAME==zyncoscope_oscope_0_1} -quiet] -quiet

# IP: bd/zyncoscope/ip/zyncoscope_axi_gpio_0_2/zyncoscope_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyncoscope_axi_gpio_0_2 || ORIG_REF_NAME==zyncoscope_axi_gpio_0_2} -quiet] -quiet

# IP: bd/zyncoscope/ip/zyncoscope_auto_pc_0/zyncoscope_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyncoscope_auto_pc_0 || ORIG_REF_NAME==zyncoscope_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/JackPaul/OneDrive/Documents/Programs/Projects/eeng498/oscope-funcgen-lab6/oscope-funcgen-lab6.gen/sources_1/bd/zyncoscope/zyncoscope_ooc.xdc
