set_property SRC_FILE_INFO {cfile:C:/Users/JackPaul/OneDrive/Documents/Programs/Projects/eeng498/arminterface-enhancedpwm-lab5/arminterface-enhancedpwm-lab5.srcs/constrs_1/new/zyncepwm.xdc rfile:../../../arminterface-enhancedpwm-lab5.srcs/constrs_1/new/zyncepwm.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17 [get_ports pwmSingal_ext_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R17 [get_ports enb_ext_0]
