set_property SRC_FILE_INFO {cfile:c:/users/jackpaul/onedrive/documents/programs/projects/eeng498/oscilloscope-lab4/oscilloscope-lab4.tmp/oscilloscope_v1_0_project/oscilloscope_v1_0_project.gen/sources_1/ip/hdmi_tx_0/hdmi_tx_0/hdmi_tx_0_in_context.xdc rfile:../../../../../../../../../../../../../../../users/jackpaul/onedrive/documents/programs/projects/eeng498/oscilloscope-lab4/oscilloscope-lab4.tmp/oscilloscope_v1_0_project/oscilloscope_v1_0_project.gen/sources_1/ip/hdmi_tx_0/hdmi_tx_0/hdmi_tx_0_in_context.xdc id:1 order:EARLY scoped_inst:oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/vgaToHdmi} [current_design]
set_property SRC_FILE_INFO {cfile:c:/users/jackpaul/onedrive/documents/programs/projects/eeng498/oscilloscope-lab4/oscilloscope-lab4.tmp/oscilloscope_v1_0_project/oscilloscope_v1_0_project.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc rfile:../../../../../../../../../../../../../../../users/jackpaul/onedrive/documents/programs/projects/eeng498/oscilloscope-lab4/oscilloscope-lab4.tmp/oscilloscope_v1_0_project/oscilloscope_v1_0_project.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc id:2 order:EARLY scoped_inst:oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/signalBRAMCh1} [current_design]
set_property SRC_FILE_INFO {cfile:c:/users/jackpaul/onedrive/documents/programs/projects/eeng498/oscilloscope-lab4/oscilloscope-lab4.tmp/oscilloscope_v1_0_project/oscilloscope_v1_0_project.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc rfile:../../../../../../../../../../../../../../../users/jackpaul/onedrive/documents/programs/projects/eeng498/oscilloscope-lab4/oscilloscope-lab4.tmp/oscilloscope_v1_0_project/oscilloscope_v1_0_project.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0/blk_mem_gen_0_in_context.xdc id:3 order:EARLY scoped_inst:oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/signalBRAMCh2} [current_design]
set_property SRC_FILE_INFO {cfile:c:/users/jackpaul/onedrive/documents/programs/projects/eeng498/oscilloscope-lab4/oscilloscope-lab4.tmp/oscilloscope_v1_0_project/oscilloscope_v1_0_project.gen/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc rfile:../../../../../../../../../../../../../../../users/jackpaul/onedrive/documents/programs/projects/eeng498/oscilloscope-lab4/oscilloscope-lab4.tmp/oscilloscope_v1_0_project/oscilloscope_v1_0_project.gen/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc id:4 order:EARLY scoped_inst:oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/vc} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports tmdsClkN_ext]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports tmdsClkN_ext]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports tmdsClkP_ext]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports tmdsClkP_ext]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {tmdsDataN_ext[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {tmdsDataN_ext[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {tmdsDataN_ext[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {tmdsDataN_ext[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {tmdsDataN_ext[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {tmdsDataN_ext[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {tmdsDataP_ext[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {tmdsDataP_ext[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {tmdsDataP_ext[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {tmdsDataP_ext[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {tmdsDataP_ext[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {tmdsDataP_ext[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/vgaToHdmi]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/signalBRAMCh1/clka]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/signalBRAMCh1/clkb]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/signalBRAMCh1]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/signalBRAMCh2/clka]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/signalBRAMCh2/clkb]
set_property src_info {type:SCOPED_XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/signalBRAMCh2]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 20.000 -name s00_axi_aclk [get_ports s00_axi_aclk]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/vc/clk_out1 -source [get_pins oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/vc/clk_in1] -edges {1 2 3} -edge_shift {0.000 -3.263 -6.526} [get_pins oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/vc/clk_out1]
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/vc/clk_out2 -source [get_pins oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/vc/clk_in1] -edges {1 2 3} -edge_shift {0.000 -8.653 -17.305} [get_pins oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/vc/clk_out2]
set_property src_info {type:SCOPED_XDC file:4 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports s00_axi_aclk]
set_property src_info {type:SCOPED_XDC file:4 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports s00_axi_aclk]
set_property src_info {type:SCOPED_XDC file:4 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/vc]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/vgaToHdmi]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/signalBRAMCh1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/signalBRAMCh2]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells oscilloscope_v1_0_S00_AXI_inst/oscilloscope/datapath/vc]
