# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zyncepwm.xdc

# Block Designs: bd/zyncepwm/zyncepwm.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyncepwm || ORIG_REF_NAME==zyncepwm} -quiet] -quiet

# IP: bd/zyncepwm/ip/zyncepwm_processing_system7_0_0/zyncepwm_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyncepwm_processing_system7_0_0 || ORIG_REF_NAME==zyncepwm_processing_system7_0_0} -quiet] -quiet

# IP: bd/zyncepwm/ip/zyncepwm_auto_pc_0/zyncepwm_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyncepwm_auto_pc_0 || ORIG_REF_NAME==zyncepwm_auto_pc_0} -quiet] -quiet

# IP: bd/zyncepwm/ip/zyncepwm_ps7_0_axi_periph_0/zyncepwm_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyncepwm_ps7_0_axi_periph_0 || ORIG_REF_NAME==zyncepwm_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zyncepwm/ip/zyncepwm_rst_ps7_0_50M_0/zyncepwm_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyncepwm_rst_ps7_0_50M_0 || ORIG_REF_NAME==zyncepwm_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/zyncepwm/ip/zyncepwm_enhancedPwm_0_0/zyncepwm_enhancedPwm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyncepwm_enhancedPwm_0_0 || ORIG_REF_NAME==zyncepwm_enhancedPwm_0_0} -quiet] -quiet

# XDC: c:/Users/JackPaul/OneDrive/Documents/Programs/Projects/eeng498/arminterface-enhancedpwm-lab5/arminterface-enhancedpwm-lab5.gen/sources_1/bd/zyncepwm/zyncepwm_ooc.xdc
